Test automation framework
NadzeyaKiz/Test-Automation-Framework pull request #1
Opened 2023-08-20 15:13 UTC by NadzeyaKiz

In TestAutomation.Epam.Tests there are tests from SeleniumAdvanced. I refactored them with my TAF.

2023-08-29 13:31 UTC, MariaEroshevich requested changes

2023-08-29 13:31 UTC, MariaEroshevich commented on code/.runsettings
> +﻿<?xml version="1.0" encoding="utf-8"?>
Add name for runsettings.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/DriverFactory.cs
> +        private static IWebDriver GetChromeConfiguredBrowser()
It is better to create separate classes for all browsers.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static string GetUrl(this IWebDriver webDriver)
add spaces

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +
remove space.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +
remove space

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static Actions GetActions(this IWebDriver webDriver)
add space

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static void ClickWithFindElement(this IWebDriver driver, By by)
I don't think that all methods that related to working with WebElement should be here.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static void WaitForCondition(this IWebDriver driver, Func<IWebDriver, bool> condition, TimeSpan timeout)
Move waiters to separate class.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Elements/WebElementExtension.cs
> +
remove spaces.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Utilities/WebDriverCookiesExtensions.cs
> +        public static void SetUpCookies(this IWebDriver driver, By locator)
This class is not related to Core layer. Move it to PageObject layer.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static TimeSpan DefaultTimeout = TimeSpan.FromMilliseconds(15000);
I think that it is better to move values for timeouts to runsettings.

2023-08-29 13:31 UTC, MariaEroshevich commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +namespace TestAutomation.Core.Browser
Implement Singleton pattern to guarantee that only one instance of driver will be created.

2023-08-30 15:57 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static string GetUrl(this IWebDriver webDriver)
done

2023-08-30 15:57 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static string GetUrl(this IWebDriver webDriver)
done

2023-08-30 15:59 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +
done

2023-08-30 16:01 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +
done

2023-08-30 16:02 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Elements/WebElementExtension.cs
> +
done

2023-09-19 21:04 UTC, merged

2023-09-24 14:30 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Browser/WebDriverExtensions.cs
> +        public static void WaitForCondition(this IWebDriver driver, Func<IWebDriver, bool> condition, TimeSpan timeout)
done