Data driven testing
NadzeyaKiz/Test-Automation-Framework pull request #2
Opened 2023-09-04 21:02 UTC by NadzeyaKiz

test 1  is completed and part of the test2

2023-09-25 21:00 UTC, MariaEroshevich requested changes

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Core/Utilities/WebDriverCookiesExtensions.cs
> +    public static class WebDriverCookiesExtensions
Move extension to the web layer.

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Epam.Tests/TestDataClasses/CareersKLFilteringTestData.cs
> +    internal class CareersKLFilteringTestData
It is enough to create one model for all test files if all test files related to CareersPage tests.

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Tests/BaseTest.cs
> +                ScreenShotTaker.CaptureScreenshot(_driver, $"success_{ TestContext.CurrentContext.Test.Name}");
it will be enough to add screenshot taker if tests fail.

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Epam.Tests/CareersPageTests.cs
> +            foreach(var element in testData)
rename element.

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Epam.Tests/TestDataClasses/TestDataClassFactory.cs
> +    public static class TestDataClassFactory
it is better to move class to the Utilities layer.

2023-09-25 21:00 UTC, MariaEroshevich commented on code/TestAutomation.Tests/BaseTest.cs
> +{
No need to create separate layer for BaseTest. Nove it to the TestAutomation.Epam.Tests.

2023-10-15 12:59 UTC, NadzeyaKiz commented on code/TestAutomation.Core/Utilities/WebDriverCookiesExtensions.cs
> +    public static class WebDriverCookiesExtensions
done

2023-10-15 12:59 UTC, NadzeyaKiz commented on code/TestAutomation.Epam.Tests/TestDataClasses/CareersKLFilteringTestData.cs
> +    internal class CareersKLFilteringTestData
done

2023-10-15 12:59 UTC, NadzeyaKiz commented on code/TestAutomation.Tests/BaseTest.cs
> +                ScreenShotTaker.CaptureScreenshot(_driver, $"success_{ TestContext.CurrentContext.Test.Name}");
ok

2023-10-15 12:59 UTC, NadzeyaKiz commented on code/TestAutomation.Epam.Tests/CareersPageTests.cs
> +            foreach(var element in testData)
ok

2023-10-15 12:59 UTC, NadzeyaKiz commented on code/TestAutomation.Epam.Tests/TestDataClasses/TestDataClassFactory.cs
> +    public static class TestDataClassFactory
ok

2023-10-15 13:00 UTC, NadzeyaKiz commented on code/TestAutomation.Tests/BaseTest.cs
> +{
ok

2023-10-15 14:08 UTC, merged